import { create } from "storybook/theming";

export const mdsStorybookTheme = create({
  base: "dark",
  brandTitle: "Miskun Design System",
  colorPrimary: "#d7ff3f",
  colorSecondary: "#d7ff3f",
  appBg: "#000000",
  appContentBg: "#050505",
  appHoverBg: "#111113",
  appPreviewBg: "#000000",
  appBorderColor: "#2a2a2e",
  appBorderRadius: 8,
  barBg: "#050505",
  barTextColor: "#d4d4d8",
  barHoverColor: "#f5f5f4",
  barSelectedColor: "#d7ff3f",
  buttonBg: "#111113",
  buttonBorder: "#2a2a2e",
  booleanBg: "#111113",
  booleanSelectedBg: "#d7ff3f",
  inputBg: "#111113",
  inputBorder: "#2a2a2e",
  inputTextColor: "#f5f5f4",
  inputBorderRadius: 8,
  fontBase: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  fontCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", monospace",
  textColor: "#f5f5f4",
  textInverseColor: "#050505",
  textMutedColor: "#a6a6ad",
});
